# Generated by Django 6.0.6 on 2026-09-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Screenshot/feedback image. Square or portrait works best, e.g. Messenger chat screenshot.', upload_to='reviews/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Choto number age dekhabe')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.review')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
