# Generated by Django 6.0.6 on 2026-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhaka_label', models.CharField(default='Inside Dhaka', max_length=100)),
                ('dhaka_charge', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('outside_label', models.CharField(default='Outside Dhaka', max_length=100)),
                ('outside_charge', models.DecimalField(decimal_places=2, default=140, max_digits=10)),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charge Settings',
            },
        ),
    ]
